---
- op: replace
  path: /spec/template/spec/containers/0/env
  value:
    - name: CASSANDRA_HOST
      value: demo-dc1-service
    - name: CASSANDRA_USER
      value: cassandra
    - name: CASSANDRA_PASSWORD
      value: cassandra
    - name: CASSANDRA_PORT
      value: "9042"
    - name: CASSANDRA_CONTACT_POINTS
      value: demo-dc1-service:9042
    - name: CASSANDRA_KEYSPACE_CQL
      value: 'CREATE KEYSPACE IF NOT EXISTS spring_petclinic WITH REPLICATION = { ''class'' : ''SimpleStrategy'', ''replication_factor'' : 1 };'
    - name: CASSANDRA_KEYSPACE_CREATE
      value: "true"
    - name: CASSANDRA_KEYSPACE_NAME
      value: spring_petclinic
    - name: CASSANDRA_LOCAL_DC
      value: dc1
    - name: CASSANDRA_USE_ASTRA
      value: "false"
    - name: DISTRIBUTED_TRACING_ENABLED
      value: "true"
    - name: DISTRIBUTED_TRACING_URL
      value: http://tracing-server:9411
    - name: LISTENING_PORT
      value: "9966"
    - name: MONITORING_ENABLED
      value: "true"
    - name: MONITORING_LISTENING_PORT
      value: "9967"
    - name: MONITORING_METRICS
      value: "true"
    - name: MONITORING_PROMETHEUS
      value: "true"
- op: replace
  path: /spec/template/spec/containers/0/image
  value: gcr.io/pixie-prod/demos/petclinic/backend:1.0@sha256:8f3bfb03da53e13d25a70291631d35aff259ce038b5dce61a8ea182766e7594b
- op: add
  path: /spec/template/spec/containers/-
  value:
    name: backend-load-generator
    image: gcr.io/pixie-oss/pixie-dev-public/curl:multiarch-7.87.0@sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
    command: ['sh', '-c', 'set -xe;
      while true; do
        sleep 2;
        curl http://${BACKEND_SERVICE}:${BACKEND_PORT}/petclinic/api/pets;
      done;']
    env:
      - name: BACKEND_SERVICE
        value: petclinic-backend
      - name: BACKEND_PORT
        value: "9966"
- op: add
  path: /spec/template/spec/initContainers
  value:
    - name: cassandra-wait
      image: cassandra:3.11.8@sha256:f38395460cdaf4ccf4da72766dd076069c39ce47ffc51e5bdfaecfca843d964a
      command: ['sh', '-c', 'set -xe;
        while ! cqlsh demo-dc1-service 9042 -u cassandra -p cassandra -e "describe cluster" ; do
          echo "waiting until cassandra is available";
          sleep 2;
        done;']
      env:
        - name: CASSANDRA_HOST
          value: demo-dc1-service
        - name: CASSANDRA_PORT
          value: "9042"
